Issue/10
0hun/delivery-service pull request #19
Opened 2021-06-10 14:36 UTC by 0hun

ControllerAdvice 적용

2021-06-11 16:17 UTC, yhmane requested changes
잘 구현  해주셨으나 테스트시 오류가 있네요
테스트코드 Bean 주입도 중요한 부분이기에 Request Changes 하도록 하겠습니다 😅

2021-06-11 16:17 UTC, yhmane commented on src/main/java/com/delivery/DeliverServiceApplication.java
> +@EnableJpaAuditing
변경된 코드는 jpaAuditingHandler 빈생성 오류를 유발합니다.

MockMVC 테스트시 해당 오류를 우회하는 여러가지 방안이 있습니다. 아래 내용을 참조하시면 무슨 말인지 이해가 되실거라 생각합니다.
https://stackoverflow.com/questions/41250177/getting-at-least-one-jpa-metamodel-must-be-present-with-webmvctest

코드 제출시 단위 테스트코드를 전부 수행하는게 좋을거 같아요 😅

2021-06-11 16:17 UTC, yhmane commented on src/main/java/com/delivery/common/exception/ExceptionController.java
> +@ControllerAdvice
```suggestion
@RestControllerAdvice
```
를 이용하면 더 간결히 처리할 수 있을텐데 @ControllerAdvice를 이용한 이유가 있을까요?

2021-06-11 16:17 UTC, yhmane commented on src/main/java/com/delivery/common/exception/ExceptionController.java
> +  @ExceptionHandler(MethodArgumentNotValidException.class)
👍

2021-06-11 16:17 UTC, yhmane commented on src/test/java/com/delivery/user/controller/UserControllerTest.java
> +            .setControllerAdvice(new ExceptionController())
👍

2021-06-11 16:37 UTC, 0hun commented on src/main/java/com/delivery/DeliverServiceApplication.java
> +@EnableJpaAuditing
네네. 테스트나 기능이 변경되었을 경우 주의해야될 사항이 있다면 주석으로 부탁드릴게요.  해당 기능은 원래대로 복구해놓겠습니다.

2021-06-11 16:45 UTC, 0hun commented on src/main/java/com/delivery/common/exception/ExceptionController.java
> +@ControllerAdvice
간결하다기보다는 RestControllerAdvice가 RestBody + ControllerAdvice를 포함하고 있는데요. 구현할 당시 RestControllerAdvice가 생각나지 않아, ControllerAdvice로 했습니다. ControllerAdvice로 바꾸면 될 것 같습니다.

2021-06-12 03:00 UTC, yhmane approved these changes
머지하겠습니다

2021-06-12 03:00 UTC, merged